// Global constants and harmless caches extracted from the legacy monolith.

// Asset publishing, locking, and refresh orchestration constants.
const ASSET_TEXT_CACHE_VERSION = "v2";
const ASSET_TEXT_CACHE_TTL_ROSTER_SECONDS = 30;
const ASSET_TEXT_CACHE_TTL_STATIC_SECONDS = 600;
const ACTIVE_ROSTER_FILENAME = "roster-data.json";
const ACTIVE_ROSTER_JOB_LOCK_KEY = "ACTIVE_ROSTER_JOB_LOCK";
const ACTIVE_ROSTER_JOB_LOCK_WAIT_MS = 30 * 1000;
const ACTIVE_ROSTER_JOB_LOCK_LEASE_MS = 15 * 60 * 1000;
const ACTIVE_ROSTER_JOB_LOCK_POLL_MS = 250;
const AUTO_REFRESH_HANDLER_NAME = "autoRefreshActiveRosterTick";
const AUTO_REFRESH_JOB_HANDLER_NAME = "autoRefreshWorkerTick";
const AUTO_REFRESH_LEGACY_JOB_HANDLER_NAME = "autoRefreshJobResumeTick";
const AUTO_REFRESH_INTERVAL_HOURS = 2;
const AUTO_REFRESH_INTERVAL_MS = AUTO_REFRESH_INTERVAL_HOURS * 60 * 60 * 1000;
const AUTO_REFRESH_ENABLED_PROPERTY = "AUTO_REFRESH_ENABLED";
const AUTO_REFRESH_TRIGGER_ID_PROPERTY = "AUTO_REFRESH_TRIGGER_ID";
const AUTO_REFRESH_JOB_TRIGGER_ID_PROPERTY = "AUTO_REFRESH_JOB_TRIGGER_ID";
const AUTO_REFRESH_JOB_PENDING_FRESH_RETRY_PROPERTY = "AUTO_REFRESH_JOB_PENDING_FRESH_RETRY";
const AUTO_REFRESH_LAST_RUN_STARTED_AT_PROPERTY = "AUTO_REFRESH_LAST_RUN_STARTED_AT";
const AUTO_REFRESH_LAST_RUN_FINISHED_AT_PROPERTY = "AUTO_REFRESH_LAST_RUN_FINISHED_AT";
const AUTO_REFRESH_LAST_RUN_STATUS_PROPERTY = "AUTO_REFRESH_LAST_RUN_STATUS";
const AUTO_REFRESH_LAST_RUN_SUMMARY_PROPERTY = "AUTO_REFRESH_LAST_RUN_SUMMARY";
const AUTO_REFRESH_LAST_ISSUE_SUMMARY_PROPERTY = "AUTO_REFRESH_LAST_ISSUE_SUMMARY";
const AUTO_REFRESH_LAST_RUN_ERROR_PROPERTY = "AUTO_REFRESH_LAST_RUN_ERROR";
const AUTO_REFRESH_LAST_RUN_ISSUE_COUNT_PROPERTY = "AUTO_REFRESH_LAST_RUN_ISSUE_COUNT";
const AUTO_REFRESH_LAST_ARCHIVE_DATE_PROPERTY = "AUTO_REFRESH_LAST_ARCHIVE_DATE";
const AUTO_REFRESH_LAST_ARCHIVE_CLEANUP_DATE_PROPERTY = "AUTO_REFRESH_LAST_ARCHIVE_CLEANUP_DATE";
const DONATION_REFRESH_HANDLER_NAME = "donationRefreshTick";
const DONATION_REFRESH_INTERVAL_MINUTES = 15;
const DONATION_REFRESH_LOCK_KEY = "DONATION_REFRESH_LOCK";
const DONATION_REFRESH_LOCK_LEASE_MS = ACTIVE_ROSTER_JOB_LOCK_LEASE_MS;
const DONATION_REFRESH_ENABLED_PROPERTY = "DONATION_REFRESH_ENABLED";
const DONATION_REFRESH_TRIGGER_ID_PROPERTY = "DONATION_REFRESH_TRIGGER_ID";
const DONATION_REFRESH_LAST_RUN_STARTED_AT_PROPERTY = "DONATION_REFRESH_LAST_RUN_STARTED_AT";
const DONATION_REFRESH_LAST_RUN_FINISHED_AT_PROPERTY = "DONATION_REFRESH_LAST_RUN_FINISHED_AT";
const DONATION_REFRESH_LAST_RUN_STATUS_PROPERTY = "DONATION_REFRESH_LAST_RUN_STATUS";
const DONATION_REFRESH_LAST_RUN_SUMMARY_PROPERTY = "DONATION_REFRESH_LAST_RUN_SUMMARY";
const DONATION_REFRESH_LAST_RUN_ERROR_PROPERTY = "DONATION_REFRESH_LAST_RUN_ERROR";
const DONATION_REFRESH_LAST_SEASON_ID_PROPERTY = "DONATION_REFRESH_LAST_SEASON_ID";
const DONATION_REFRESH_LAST_WRITE_AT_PROPERTY = "DONATION_REFRESH_LAST_WRITE_AT";
const REGULAR_WAR_FINALIZATION_HANDLER_NAME = "regularWarFinalizationTick";
const REGULAR_WAR_FINALIZATION_TRIGGER_ID_PROPERTY = "REGULAR_WAR_FINALIZATION_TRIGGER_ID";
const REGULAR_WAR_FINALIZATION_TRIGGER_AT_PROPERTY = "REGULAR_WAR_FINALIZATION_TRIGGER_AT";
const REGULAR_WAR_FINALIZATION_INITIAL_DELAY_MS = 2 * 60 * 1000;
const REGULAR_WAR_FINALIZATION_MIN_TRIGGER_DELAY_MS = 60 * 1000;
const REGULAR_WAR_FINALIZATION_RETRY_DELAYS_MS = [10 * 60 * 1000, 30 * 60 * 1000, 60 * 60 * 1000, 2 * 60 * 60 * 1000];
const ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_AT_PROPERTY = "ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_AT";
const ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_SOURCE_PROPERTY = "ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_SOURCE";
const ACTIVE_DATA_WRITE_SOURCE_UNKNOWN = "unknown";
const ACTIVE_DATA_WRITE_SOURCE_PUBLISH = "publish";
const ACTIVE_DATA_WRITE_SOURCE_AUTO_REFRESH = "auto-refresh";
const ACTIVE_DATA_WRITE_SOURCE_DISCORD_SYNC = "discord-sync";
const STATIC_ASSET_BASE_URL = "https://turtlecoc.4jbf82gng5.workers.dev/";
const STATIC_ASSET_VERSION_PROPERTY = "STATIC_ASSET_VERSION";
const STATIC_ASSET_VERSION_FALLBACK = "v1";
const CLOUDFLARE_PUBLIC_DATA_BASE_URL_PROPERTY = "CLOUDFLARE_PUBLIC_DATA_BASE_URL";
const CLOUDFLARE_PUBLIC_DATA_PUBLISH_SECRET_PROPERTY = "CLOUDFLARE_PUBLIC_DATA_PUBLISH_SECRET";
const CLOUDFLARE_PUBLIC_DATA_ENABLED_PROPERTY = "CLOUDFLARE_PUBLIC_DATA_ENABLED";
const CLOUDFLARE_PUBLIC_DATA_LAST_PUBLISH_AT_PROPERTY = "CLOUDFLARE_PUBLIC_DATA_LAST_PUBLISH_AT";
const CLOUDFLARE_PUBLIC_DATA_LAST_PUBLISH_STATUS_PROPERTY = "CLOUDFLARE_PUBLIC_DATA_LAST_PUBLISH_STATUS";
const CLOUDFLARE_PUBLIC_DATA_LAST_PUBLISH_ERROR_PROPERTY = "CLOUDFLARE_PUBLIC_DATA_LAST_PUBLISH_ERROR";
const FIREBASE_KEY_ENCODING_PREFIX = "__FB64__";
const FIREBASE_LAYOUT_VERSION = 2;
const FIREBASE_ACTIVE_PATH = "active";
const FIREBASE_ACTIVE_PUBLISHED_PATH = "activePublished";
const FIREBASE_ACTIVE_PUBLISHED_CURRENT_VERSION_PATH = "activePublished/currentVersionId";
const FIREBASE_ACTIVE_PUBLISHED_CURRENT_MANIFEST_PATH = "activePublished/currentManifest";
const FIREBASE_ACTIVE_VERSIONS_PATH = "activeVersions";
const FIREBASE_ARCHIVE_PUBLISH_PATH = "archive/publish";
const FIREBASE_ARCHIVE_AUTOREFRESH_DAILY_PATH = "archive/autorefreshDaily";
const FIREBASE_DONATION_REFRESH_PATH = "donationRefresh";
const FIREBASE_INTERNAL_AUTO_REFRESH_JOB_PATH = "internal/autoRefresh/current";
const FIREBASE_INTERNAL_AUTO_REFRESH_LAST_JOB_PATH = "internal/autoRefresh/lastJob";
const FIREBASE_INTERNAL_AUTO_REFRESH_RUNS_PATH = "internal/autoRefresh/runs";
const FIREBASE_META_PATH = "meta";
const FIREBASE_PUBLISH_ARCHIVE_KEEP_COUNT = 10;
const FIREBASE_AUTOREFRESH_DAILY_KEEP_COUNT = 2;
const FIREBASE_DONATION_REFRESH_SEASON_KEEP_COUNT = 16;
const FIREBASE_ACTIVE_VERSION_HISTORY_KEEP_COUNT = 0;
const FIREBASE_AUTOREFRESH_RUN_HISTORY_KEEP_COUNT = 0;
const FIREBASE_ACCESS_TOKEN_CACHE_KEY = "firebaseAccessToken:v1";
const FIREBASE_ACCESS_TOKEN_SCOPE = "https://www.googleapis.com/auth/firebase.database https://www.googleapis.com/auth/userinfo.email";
const FIREBASE_ACCESS_TOKEN_TTL_SAFETY_SECONDS = 60;
const CACHE_SAFE_TEXT_MAX_CHARS = 90 * 1024;
let staticAssetVersionCache_ = null;
let firebaseConfigCache_ = null;

// External service, roster-tracking, and metrics retention constants.
const COC_PROXY_BASE_URL = "https://cocproxy.royaleapi.dev/v1";
const PLAYER_PROFILE_CACHE_TTL_SECONDS = 300;
const TOWN_HALL_ICON_CACHE_TTL_SECONDS = 3600;
const LEAGUE_ICON_CACHE_TTL_SECONDS = 3600;
const LEAGUE_ICON_CACHE_VERSION = "v4";
const CWL_PREPARATION_ALGORITHM = "strength_top_x_v1";
const CWL_PREPARATION_MIN_ROSTER_SIZE = 5;
const CWL_PREPARATION_MAX_ROSTER_SIZE = 50;
const CWL_PREPARATION_ROSTER_SIZE_STEP = 5;
// How long to retain a member's tracking data after they stop appearing in the roster.
// This is intentionally long (e.g., 28 days) to avoid losing war history for temporary departures.
const REGULAR_WAR_MISSING_GRACE_MS = 28 * 24 * 60 * 60 * 1000; // 28 days
const REGULAR_WAR_WARLOG_LIMIT = 25;
const REGULAR_WAR_REPAIR_GRACE_MS = 6 * 60 * 60 * 1000; // 6 hours
const ACTIVE_ROSTER_LOCK_HEARTBEAT_MIN_INTERVAL_MS = 15 * 1000;
const AUTO_REFRESH_PREFETCH_BATCH_SIZE = 8;
const AUTO_REFRESH_PREFETCH_BATCH_DELAY_MS = 1000;
const AUTO_REFRESH_JOB_EXECUTION_BUDGET_MS = 270 * 1000;
const AUTO_REFRESH_JOB_RESUME_DELAY_MS = 60 * 1000;
const AUTO_REFRESH_QUEUE_TASK_STALE_MS = 8 * 60 * 1000;
const AUTO_REFRESH_QUEUE_WORKER_START_RESERVE_MS = 90 * 1000;
const AUTO_REFRESH_QUEUE_FINALIZE_RESERVE_MS = 120 * 1000;
const AUTO_REFRESH_QUEUE_ROSTER_PROCESS_RESERVE_MS = 120 * 1000;
const AUTO_REFRESH_QUEUE_ROSTER_WRITE_RESERVE_MS = 60 * 1000;
const AUTO_REFRESH_METRIC_COPY_TASK_TAG_LIMIT = 100;
const COC_FETCH_MAX_ATTEMPTS = 3;
const COC_FETCH_RETRY_BASE_DELAY_MS = 300;
const COC_FETCH_RETRY_MIN_DELAY_MS = 150;
const COC_FETCH_RETRY_MAX_DELAY_MS = 2500;
const PLAYER_METRICS_SCHEMA_VERSION = 1;
const PLAYER_METRICS_TROPHY_HISTORY_MAX_DAYS = 120;
const PLAYER_METRICS_DONATION_CYCLES_MAX = 16;
const PLAYER_METRICS_ENTRY_RETENTION_DAYS = 240;
const PLAYER_METRICS_PLAYER_HOUSE_MAX_ELEMENTS = 8;
const PLAYER_METRICS_MIN_ROSTER_COVERAGE_FOR_PUBLISH = 0.9;
let activeRosterLockContextStack_ = [];

// Bench planner weights and solver limits.
const CWL_BENCH_PLANNER_CONFIG = {
	algorithm: "cwl_bench_exact_dp_v2",
	defaultSeasonDays: 7,
	// Legacy strength scorer inputs are still used by CWL Preparation Mode.
	priorMeanStarsPerStart: 2.0,
	priorWeightAttacks: 2.5,
	minExpectedStarsPerStart: 1.25,
	maxExpectedStarsPerStart: 2.75,
	perfPriorWeight: 3.0,
	starsPerfPriorMean: 0.5,
	destructionPerfPriorMean: 0.5,
	threeStarRatePriorWeight: 4.0,
	reliabilityPriorWeight: 2.5,
	weightTH: 0.38,
	weightStarsPerf: 0.22,
	weightDestructionPerf: 0.14,
	weightThreeStarRate: 0.1,
	weightHitUpAbility: 0.08,
	weightHitEvenAbility: 0.08,
	weightReliabilityPenalty: 0.2,
	churnPenalty: 0.03,
	reasonStrengthDeltaThreshold: 0.05,
	// Bench planner v2 uses a separate fixed-scale value model.
	supportedTownHallMin: 1,
	supportedTownHallMax: 18,
	unknownTownHallNormalized: 0.5,
	qualityPriorMeanStarsWhenUsed: 3.0,
	qualityPriorMeanDestruction: 100.0,
	qualityPriorMeanThreeStarProbability: 1.0,
	qualityPriorWeightAttacks: 2.0,
	reliabilityPriorMean: 0.98,
	reliabilityPriorWeight: 5.0,
	currentCwlQualityWeight: 1.0,
	previousCwlQualityWeight: 0.7,
	regularWarQualityWeight: 0.35,
	currentCwlReliabilityWeight: 1.0,
	previousCwlReliabilityWeight: 0.7,
	regularWarReliabilityWeight: 0.35,
	previousCwlMaxAttacks: 12,
	regularWarMaxAttacks: 24,
	previousCwlMaxOpportunities: 12,
	regularWarMaxOpportunities: 30,
	benchWeightTownHall: 0.42,
	benchWeightStarsWhenUsed: 0.28,
	benchWeightDestructionWhenUsed: 0.12,
	benchWeightThreeStarProbability: 0.12,
	benchReliabilityExponent: 1.35,
	rewardSelectionValueScale: 100000,
	baselineValueScale: 100000,
	optionalSwapMinScoreDelta: 0.08,
	maxOptionalSwaps: 2,
	reasonReliabilityDeltaThreshold: 0.12,
	rewardOptimizerMaxPlayers: 60,
	rewardOptimizerMaxCapacity: 240,
	optimizerMaxPlayers: 42,
	optimizerMaxDays: 8,
	optimizerMaxStateCells: 250000,
	optimizerScoreScale: 100000,
};
