// Global constants and harmless caches extracted from the legacy monolith.

// Asset publishing, locking, and refresh orchestration constants.
const ASSET_TEXT_CACHE_VERSION = "v2";
const ASSET_TEXT_CACHE_TTL_ROSTER_SECONDS = 30;
const ASSET_TEXT_CACHE_TTL_STATIC_SECONDS = 600;
const ACTIVE_ROSTER_FILENAME = "roster-data.json";
const ACTIVE_ROSTER_JOB_LOCK_KEY = "ACTIVE_ROSTER_JOB_LOCK";
const ACTIVE_ROSTER_JOB_LOCK_WAIT_MS = 30 * 1000;
const ACTIVE_ROSTER_JOB_LOCK_LEASE_MS = 15 * 60 * 1000;
const ACTIVE_ROSTER_JOB_LOCK_POLL_MS = 250;
const AUTO_REFRESH_HANDLER_NAME = "autoRefreshActiveRosterTick";
const AUTO_REFRESH_JOB_HANDLER_NAME = "autoRefreshJobResumeTick";
const AUTO_REFRESH_INTERVAL_HOURS = 2;
const AUTO_REFRESH_INTERVAL_MS = AUTO_REFRESH_INTERVAL_HOURS * 60 * 60 * 1000;
const AUTO_REFRESH_ENABLED_PROPERTY = "AUTO_REFRESH_ENABLED";
const AUTO_REFRESH_TRIGGER_ID_PROPERTY = "AUTO_REFRESH_TRIGGER_ID";
const AUTO_REFRESH_JOB_TRIGGER_ID_PROPERTY = "AUTO_REFRESH_JOB_TRIGGER_ID";
const AUTO_REFRESH_JOB_PENDING_FRESH_RETRY_PROPERTY = "AUTO_REFRESH_JOB_PENDING_FRESH_RETRY";
const AUTO_REFRESH_LAST_RUN_STARTED_AT_PROPERTY = "AUTO_REFRESH_LAST_RUN_STARTED_AT";
const AUTO_REFRESH_LAST_RUN_FINISHED_AT_PROPERTY = "AUTO_REFRESH_LAST_RUN_FINISHED_AT";
const AUTO_REFRESH_LAST_RUN_STATUS_PROPERTY = "AUTO_REFRESH_LAST_RUN_STATUS";
const AUTO_REFRESH_LAST_RUN_SUMMARY_PROPERTY = "AUTO_REFRESH_LAST_RUN_SUMMARY";
const AUTO_REFRESH_LAST_ISSUE_SUMMARY_PROPERTY = "AUTO_REFRESH_LAST_ISSUE_SUMMARY";
const AUTO_REFRESH_LAST_RUN_ERROR_PROPERTY = "AUTO_REFRESH_LAST_RUN_ERROR";
const AUTO_REFRESH_LAST_RUN_ISSUE_COUNT_PROPERTY = "AUTO_REFRESH_LAST_RUN_ISSUE_COUNT";
const AUTO_REFRESH_LAST_ARCHIVE_DATE_PROPERTY = "AUTO_REFRESH_LAST_ARCHIVE_DATE";
const AUTO_REFRESH_LAST_ARCHIVE_CLEANUP_DATE_PROPERTY = "AUTO_REFRESH_LAST_ARCHIVE_CLEANUP_DATE";
const REGULAR_WAR_FINALIZATION_HANDLER_NAME = "regularWarFinalizationTick";
const REGULAR_WAR_FINALIZATION_TRIGGER_ID_PROPERTY = "REGULAR_WAR_FINALIZATION_TRIGGER_ID";
const REGULAR_WAR_FINALIZATION_TRIGGER_AT_PROPERTY = "REGULAR_WAR_FINALIZATION_TRIGGER_AT";
const REGULAR_WAR_FINALIZATION_INITIAL_DELAY_MS = 2 * 60 * 1000;
const REGULAR_WAR_FINALIZATION_MIN_TRIGGER_DELAY_MS = 60 * 1000;
const REGULAR_WAR_FINALIZATION_RETRY_DELAYS_MS = [10 * 60 * 1000, 30 * 60 * 1000, 60 * 60 * 1000, 2 * 60 * 60 * 1000];
const ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_AT_PROPERTY = "ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_AT";
const ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_SOURCE_PROPERTY = "ACTIVE_DATA_LAST_SUCCESSFUL_WRITE_SOURCE";
const ACTIVE_DATA_WRITE_SOURCE_UNKNOWN = "unknown";
const ACTIVE_DATA_WRITE_SOURCE_PUBLISH = "publish";
const ACTIVE_DATA_WRITE_SOURCE_AUTO_REFRESH = "auto-refresh";
const ACTIVE_DATA_WRITE_SOURCE_DISCORD_SYNC = "discord-sync";
const STATIC_ASSET_BASE_URL = "https://turtlecoc.4jbf82gng5.workers.dev/";
const STATIC_ASSET_VERSION_PROPERTY = "STATIC_ASSET_VERSION";
const STATIC_ASSET_VERSION_FALLBACK = "v1";
const FIREBASE_KEY_ENCODING_PREFIX = "__FB64__";
const FIREBASE_LAYOUT_VERSION = 2;
const FIREBASE_ACTIVE_PATH = "active";
const FIREBASE_ARCHIVE_PUBLISH_PATH = "archive/publish";
const FIREBASE_ARCHIVE_AUTOREFRESH_DAILY_PATH = "archive/autorefreshDaily";
const FIREBASE_INTERNAL_AUTO_REFRESH_JOB_PATH = "internal/autoRefresh/current";
const FIREBASE_INTERNAL_AUTO_REFRESH_LAST_JOB_PATH = "internal/autoRefresh/lastJob";
const FIREBASE_META_PATH = "meta";
const FIREBASE_PUBLISH_ARCHIVE_KEEP_COUNT = 10;
const FIREBASE_AUTOREFRESH_DAILY_KEEP_COUNT = 2;
const FIREBASE_ACCESS_TOKEN_CACHE_KEY = "firebaseAccessToken:v1";
const FIREBASE_ACCESS_TOKEN_SCOPE = "https://www.googleapis.com/auth/firebase.database https://www.googleapis.com/auth/userinfo.email";
const FIREBASE_ACCESS_TOKEN_TTL_SAFETY_SECONDS = 60;
const CACHE_SAFE_TEXT_MAX_CHARS = 90 * 1024;
let staticAssetVersionCache_ = null;
let firebaseConfigCache_ = null;

// External service, roster-tracking, and metrics retention constants.
const COC_PROXY_BASE_URL = "https://cocproxy.royaleapi.dev/v1";
const PLAYER_PROFILE_CACHE_TTL_SECONDS = 300;
const TOWN_HALL_ICON_CACHE_TTL_SECONDS = 3600;
const LEAGUE_ICON_CACHE_TTL_SECONDS = 3600;
const LEAGUE_ICON_CACHE_VERSION = "v4";
const CWL_PREPARATION_ALGORITHM = "strength_top_x_v1";
const CWL_PREPARATION_MIN_ROSTER_SIZE = 5;
const CWL_PREPARATION_MAX_ROSTER_SIZE = 50;
const CWL_PREPARATION_ROSTER_SIZE_STEP = 5;
// How long to retain a member's tracking data after they stop appearing in the roster.
// This is intentionally long (e.g., 28 days) to avoid losing war history for temporary departures.
const REGULAR_WAR_MISSING_GRACE_MS = 28 * 24 * 60 * 60 * 1000; // 28 days
const REGULAR_WAR_WARLOG_LIMIT = 25;
const REGULAR_WAR_REPAIR_GRACE_MS = 6 * 60 * 60 * 1000; // 6 hours
const ACTIVE_ROSTER_LOCK_HEARTBEAT_MIN_INTERVAL_MS = 15 * 1000;
const AUTO_REFRESH_PREFETCH_BATCH_SIZE = 8;
const AUTO_REFRESH_PREFETCH_BATCH_DELAY_MS = 1000;
const AUTO_REFRESH_JOB_EXECUTION_BUDGET_MS = 270 * 1000;
const AUTO_REFRESH_JOB_STATE_WRITE_RESERVE_MS = 135 * 1000;
const AUTO_REFRESH_JOB_ROSTER_START_RESERVE_MS = AUTO_REFRESH_JOB_STATE_WRITE_RESERVE_MS + 45 * 1000;
const AUTO_REFRESH_JOB_FINALIZE_RESERVE_MS = 210 * 1000;
const AUTO_REFRESH_JOB_SOURCE_GUARD_RESERVE_MS = 150 * 1000;
const AUTO_REFRESH_JOB_ACTIVE_COMMIT_RESERVE_MS = 100 * 1000;
const AUTO_REFRESH_JOB_STALE_CLEANUP_RESERVE_MS = 30 * 1000;
const AUTO_REFRESH_JOB_COMMIT_RESERVE_MS = AUTO_REFRESH_JOB_FINALIZE_RESERVE_MS;
const AUTO_REFRESH_JOB_RESUME_DELAY_MS = 60 * 1000;
const COC_FETCH_MAX_ATTEMPTS = 3;
const COC_FETCH_RETRY_BASE_DELAY_MS = 300;
const COC_FETCH_RETRY_MIN_DELAY_MS = 150;
const COC_FETCH_RETRY_MAX_DELAY_MS = 2500;
const PLAYER_METRICS_SCHEMA_VERSION = 1;
const PLAYER_METRICS_TROPHY_HISTORY_MAX_DAYS = 120;
const PLAYER_METRICS_DONATION_CYCLES_MAX = 16;
const PLAYER_METRICS_ENTRY_RETENTION_DAYS = 240;
const PLAYER_METRICS_PLAYER_HOUSE_MAX_ELEMENTS = 8;
const PLAYER_METRICS_MIN_ROSTER_COVERAGE_FOR_PUBLISH = 0.9;
let activeRosterLockContextStack_ = [];

// Bench planner weights and solver limits.
const CWL_BENCH_PLANNER_CONFIG = {
	algorithm: "season_milp_v1",
	defaultSeasonDays: 7,
	priorMeanStarsPerStart: 2.0,
	priorWeightAttacks: 2.5,
	minExpectedStarsPerStart: 1.25,
	maxExpectedStarsPerStart: 2.75,
	perfPriorWeight: 3.0,
	starsPerfPriorMean: 0.5,
	destructionPerfPriorMean: 0.5,
	threeStarRatePriorWeight: 4.0,
	reliabilityPriorWeight: 2.5,
	weightTH: 0.38,
	weightStarsPerf: 0.22,
	weightDestructionPerf: 0.14,
	weightThreeStarRate: 0.1,
	weightHitUpAbility: 0.08,
	weightHitEvenAbility: 0.08,
	weightReliabilityPenalty: 0.2,
	churnPenalty: 0.03,
	reasonStrengthDeltaThreshold: 0.05,
	optimizerMaxPlayers: 42,
	optimizerMaxDays: 8,
	optimizerMaxStateCells: 250000,
	optimizerScoreScale: 100000,
};
